# Generated by Django 5.2.9 on 2026-01-06 06:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("free", "Free"), ("pro", "Pro")],
                        db_index=True,
                        default="free",
                        max_length=20,
                    ),
                ),
                ("remaining_documents", models.IntegerField(default=0)),
                ("remaining_chats", models.IntegerField(default=0)),
                ("last_reset_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "plan",
            },
        ),
    ]
