/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LabRouteImport } from './routes/lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as LabUsageRouteImport } from './routes/lab/usage'
import { Route as LabProfileRouteImport } from './routes/lab/profile'
import { Route as LabHistoryRouteImport } from './routes/lab/history'
import { Route as LabDocumentsRouteImport } from './routes/lab/documents'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as LabChatIndexRouteImport } from './routes/lab/chat/index'
import { Route as LabChatNewRouteImport } from './routes/lab/chat/new'
import { Route as LabChatChatSessionIdRouteImport } from './routes/lab/chat/$chatSessionId'

const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRoute,
} as any)
const LabUsageRoute = LabUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => LabRoute,
} as any)
const LabProfileRoute = LabProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LabRoute,
} as any)
const LabHistoryRoute = LabHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LabRoute,
} as any)
const LabDocumentsRoute = LabDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LabRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const LabChatIndexRoute = LabChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => LabRoute,
} as any)
const LabChatNewRoute = LabChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => LabRoute,
} as any)
const LabChatChatSessionIdRoute = LabChatChatSessionIdRouteImport.update({
  id: '/chat/$chatSessionId',
  path: '/chat/$chatSessionId',
  getParentRoute: () => LabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/auth/signin': typeof AuthSigninRoute
  '/lab/documents': typeof LabDocumentsRoute
  '/lab/history': typeof LabHistoryRoute
  '/lab/profile': typeof LabProfileRoute
  '/lab/usage': typeof LabUsageRoute
  '/lab/': typeof LabIndexRoute
  '/lab/chat/$chatSessionId': typeof LabChatChatSessionIdRoute
  '/lab/chat/new': typeof LabChatNewRoute
  '/lab/chat': typeof LabChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/signin': typeof AuthSigninRoute
  '/lab/documents': typeof LabDocumentsRoute
  '/lab/history': typeof LabHistoryRoute
  '/lab/profile': typeof LabProfileRoute
  '/lab/usage': typeof LabUsageRoute
  '/lab': typeof LabIndexRoute
  '/lab/chat/$chatSessionId': typeof LabChatChatSessionIdRoute
  '/lab/chat/new': typeof LabChatNewRoute
  '/lab/chat': typeof LabChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/auth/signin': typeof AuthSigninRoute
  '/lab/documents': typeof LabDocumentsRoute
  '/lab/history': typeof LabHistoryRoute
  '/lab/profile': typeof LabProfileRoute
  '/lab/usage': typeof LabUsageRoute
  '/lab/': typeof LabIndexRoute
  '/lab/chat/$chatSessionId': typeof LabChatChatSessionIdRoute
  '/lab/chat/new': typeof LabChatNewRoute
  '/lab/chat/': typeof LabChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/auth/error'
    | '/auth/signin'
    | '/lab/documents'
    | '/lab/history'
    | '/lab/profile'
    | '/lab/usage'
    | '/lab/'
    | '/lab/chat/$chatSessionId'
    | '/lab/chat/new'
    | '/lab/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/error'
    | '/auth/signin'
    | '/lab/documents'
    | '/lab/history'
    | '/lab/profile'
    | '/lab/usage'
    | '/lab'
    | '/lab/chat/$chatSessionId'
    | '/lab/chat/new'
    | '/lab/chat'
  id:
    | '__root__'
    | '/'
    | '/lab'
    | '/auth/error'
    | '/auth/signin'
    | '/lab/documents'
    | '/lab/history'
    | '/lab/profile'
    | '/lab/usage'
    | '/lab/'
    | '/lab/chat/$chatSessionId'
    | '/lab/chat/new'
    | '/lab/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  AuthSigninRoute: typeof AuthSigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/usage': {
      id: '/lab/usage'
      path: '/usage'
      fullPath: '/lab/usage'
      preLoaderRoute: typeof LabUsageRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/profile': {
      id: '/lab/profile'
      path: '/profile'
      fullPath: '/lab/profile'
      preLoaderRoute: typeof LabProfileRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/history': {
      id: '/lab/history'
      path: '/history'
      fullPath: '/lab/history'
      preLoaderRoute: typeof LabHistoryRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/documents': {
      id: '/lab/documents'
      path: '/documents'
      fullPath: '/lab/documents'
      preLoaderRoute: typeof LabDocumentsRouteImport
      parentRoute: typeof LabRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/chat/': {
      id: '/lab/chat/'
      path: '/chat'
      fullPath: '/lab/chat'
      preLoaderRoute: typeof LabChatIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/chat/new': {
      id: '/lab/chat/new'
      path: '/chat/new'
      fullPath: '/lab/chat/new'
      preLoaderRoute: typeof LabChatNewRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/chat/$chatSessionId': {
      id: '/lab/chat/$chatSessionId'
      path: '/chat/$chatSessionId'
      fullPath: '/lab/chat/$chatSessionId'
      preLoaderRoute: typeof LabChatChatSessionIdRouteImport
      parentRoute: typeof LabRoute
    }
  }
}

interface LabRouteChildren {
  LabDocumentsRoute: typeof LabDocumentsRoute
  LabHistoryRoute: typeof LabHistoryRoute
  LabProfileRoute: typeof LabProfileRoute
  LabUsageRoute: typeof LabUsageRoute
  LabIndexRoute: typeof LabIndexRoute
  LabChatChatSessionIdRoute: typeof LabChatChatSessionIdRoute
  LabChatNewRoute: typeof LabChatNewRoute
  LabChatIndexRoute: typeof LabChatIndexRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabDocumentsRoute: LabDocumentsRoute,
  LabHistoryRoute: LabHistoryRoute,
  LabProfileRoute: LabProfileRoute,
  LabUsageRoute: LabUsageRoute,
  LabIndexRoute: LabIndexRoute,
  LabChatChatSessionIdRoute: LabChatChatSessionIdRoute,
  LabChatNewRoute: LabChatNewRoute,
  LabChatIndexRoute: LabChatIndexRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  AuthSigninRoute: AuthSigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
