# Generated by Django 5.2.9 on 2025-12-28 22:44

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("upload", "Upload"), ("url", "URL"), ("internal", "Internal")],
                        default="upload",
                        max_length=64,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "storage_url",
                    models.CharField(blank=True, default=None, max_length=2048, null=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("txt", "Text"),
                            ("md", "Markdown"),
                            ("html", "HTML"),
                            ("other", "Other"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                    ),
                ),
                ("size_kb", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("summary", models.TextField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.IntegerField()),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="document.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_chunks",
                "ordering": ["document", "order"],
                "indexes": [
                    models.Index(
                        fields=["document", "order"], name="document_ch_documen_e0beb9_idx"
                    )
                ],
                "unique_together": {("document", "order")},
            },
        ),
    ]
